services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Jenkinsfile:/var/jenkins_home/Jenkinsfile
      - ./jenkins-config.yaml:/usr/share/jenkins/ref/jenkins-config.yaml
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge

volumes:
  jenkins_home:
