version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"    # Jenkins web UI
      - "50001:50000"  # Agentes remotos Jenkins (Jenkins slave)
    volumes:
      - jenkins_home:/var/jenkins_home          # Persistencia datos Jenkins
      - /var/run/docker.sock:/var/run/docker.sock   # Acceso Docker host
      - ./Jenkinsfile:/var/jenkins_home/Jenkinsfile # Opcional: pipeline en workspace Jenkins
      - ./jenkins-config.yaml:/usr/share/jenkins/ref/jenkins-config.yaml # Config automática Jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge

volumes:
  jenkins_home:

