version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: bash -c "pip install -e . && bash"
    tty: true
    stdin_open: true

  tests:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: bash -c "pip install -e . && pytest -v"
    depends_on:
      - app

  lint:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: >
      bash -c "
        pip install -e . &&
        black --check . &&
        flake8 . &&
        mypy . &&
        echo 'All checks passed!'
      "
    depends_on:
      - app
